### ISSUE TITLE
RemoveCopyIfIn logic is backwards (bug)

### ISSUE THREAD

**Issue by dougwinsby** [Olray/DeCAL#1]
I think I saw this bug in an SDL forum long, long ago...

The docs say:

> The `removeCopy` algorithm copies a sequence of items from one location to another, removing any matching items as it goes.

and the comment for that routine says:

```pascal
  {** Copies the source range to the destination, except for those items
  for which test returns true. }
	function removeCopyIfIn(_start, _end, dest : DIterator; test : DTest) : DIterator;
```

But the code appears to **include** the item in the destination if the test is true (instead of skipping it):

```pascal
      o := getRef(_start);
      if test(o^) then
        begin
          _output(dest, o^);
        end;
```

It should probably be:

```pascal
if not test(o^) then
```

https://github.com/Olray/DeCAL/blob/36b33d46fed9020cd67cdccebb04387bedd0e363/DeCAL.pas#L10527

**Comment by Olray** [comment]
I wrote a test to verify the bug and the correct behavior of the fix. However, fixing a bug that is 25 years old is risky, The lib is intended to be a drop-in replacement for old projects, Perhaps some people found the bug and worked around it. So I have marked the function removeCopyIfIn() as deprecated and added a message that's hopefully leading to this documentation.

Thanks for reporting.
